export const items: Record<string, string> = {
  "Recombobulator 3000": "RECOMBOBULATOR_3000",
  "Bonzo's Staff": "BONZO_STAFF",
  "Fuming Potato Book": "FUMING_POTATO_BOOK",
  "Bonzo's Mask": "BONZO_MASK",
  "Red Nose": "RED_NOSE",
  "Hot Potato Book": "HOT_POTATO_BOOK",
  "No Pain No Gain I": "ENCHANTED_BOOK-ULTIMATE_NO_PAIN_NO_GAIN-1",
  "No Pain No Gain II": "ENCHANTED_BOOK-ULTIMATE_NO_PAIN_NO_GAIN-2",
  "No Pain No Gain III": "ENCHANTED_BOOK-ULTIMATE_NO_PAIN_NO_GAIN-3",
  "Ultimate Jerry I": "ENCHANTED_BOOK-ULTIMATE_JERRY-1",
  "Ultimate Jerry II": "ENCHANTED_BOOK-ULTIMATE_JERRY-2",
  "Ultimate Jerry III": "ENCHANTED_BOOK-ULTIMATE_JERRY-3",
  "Bank I": "ENCHANTED_BOOK-ULTIMATE_BANK-1",
  "Bank II": "ENCHANTED_BOOK-ULTIMATE_BANK-2",
  "Bank III": "ENCHANTED_BOOK-ULTIMATE_BANK-3",
  "One For All I": "ENCHANTED_BOOK-ULTIMATE_ONE_FOR_ALL-1",
  "Soul Eater I": "ENCHANTED_BOOK-ULTIMATE_SOUL_EATER-1",
  "Combo I": "ENCHANTED_BOOK-ULTIMATE_COMBO-1",
  "Combo II": "ENCHANTED_BOOK-ULTIMATE_COMBO-2",
  "Combo III": "ENCHANTED_BOOK-ULTIMATE_COMBO-3",
  "Infinite Quiver VI": "ENCHANTED_BOOK-INFINITE_QUIVER-6",
  "Infinite Quiver VII": "ENCHANTED_BOOK-INFINITE_QUIVER-7",
  "Infinite Quiver VIII": "ENCHANTED_BOOK-INFINITE_QUIVER-8",
  "Feather Falling VI": "ENCHANTED_BOOK-FEATHER_FALLING-6",
  "Feather Falling VII": "ENCHANTED_BOOK-FEATHER_FALLING-7",
  "Feather Falling VIII": "ENCHANTED_BOOK-FEATHER_FALLING-8",
  "Rejuvenate I": "ENCHANTED_BOOK-REJUVENATE-1",
  "Rejuvenate II": "ENCHANTED_BOOK-REJUVENATE-2",
  "Rejuvenate III": "ENCHANTED_BOOK-REJUVENATE-3",
  "Ultimate Wise I": "ENCHANTED_BOOK-ULTIMATE_WISE-1",
  "Ultimate Wise II": "ENCHANTED_BOOK-ULTIMATE_WISE-2",
  "Ultimate Wise III": "ENCHANTED_BOOK-ULTIMATE_WISE-3",
  "Wisdom I": "ENCHANTED_BOOK-ULTIMATE_WISDOM-1",
  "Wisdom II": "ENCHANTED_BOOK-ULTIMATE_WISDOM-2",
  "Wisdom III": "ENCHANTED_BOOK-ULTIMATE_WISDOM-3",
  "Last Stand I": "ENCHANTED_BOOK-ULTIMATE_LAST_STAND-1",
  "Last Stand II": "ENCHANTED_BOOK-ULTIMATE_LAST_STAND-2",
  "Last Stand III": "ENCHANTED_BOOK-ULTIMATE_LAST_STAND-3",
  "Rend I": "ENCHANTED_BOOK-ULTIMATE_REND-1",
  "Rend II": "ENCHANTED_BOOK-ULTIMATE_REND-2",
  "Rend III": "ENCHANTED_BOOK-ULTIMATE_REND-3",
  "Spirit Bone": "SPIRIT_BONE",
  "Spirit Wing": "SPIRIT_WING",
  "Thunderlord VII": "ENCHANTED_BOOK-THUNDERLORD-7",
  "Suspicious Vial": "SUSPICIOUS_VIAL",
  "Dark Claymore": "DARK_CLAYMORE",
  "Necron Dye": "DYE_NECRON",
  "Master Skull - Tier 1": "MASTER_SKULL_TIER_1",
  "Master Skull - Tier 2": "MASTER_SKULL_TIER_2",
  "Master Skull - Tier 3": "MASTER_SKULL_TIER_3",
  "Master Skull - Tier 4": "MASTER_SKULL_TIER_4",
  "Master Skull - Tier 5": "MASTER_SKULL_TIER_5",
  "First Master Star": "FIRST_MASTER_STAR",
  "Second Master Star": "SECOND_MASTER_STAR",
  "Third Master Star": "THIRD_MASTER_STAR",
  "Fourth Master Star": "FOURTH_MASTER_STAR",
  "Fifth Master Star": "FIFTH_MASTER_STAR",
  "Necron’s Handle": "NECRON_HANDLE",
  "Necron's Handle": "NECRON_HANDLE",
  "Necromancer's Brooch": "NECROMANCER_BROOCH",
  "Adaptive Blade": "STONE_BLADE",
  "Adaptive Boots": "ADAPTIVE_BOOTS",
  "Adaptive Leggings": "ADAPTIVE_LEGGINGS",
  "Adaptive Chestplate": "ADAPTIVE_CHESTPLATE",
  "Adaptive Helmet": "ADAPTIVE_HELMET",
  "Red Scarf": "RED_SCARF",
  "Scarf's Studies": "SCARF_STUDIES",
  "Legendary Spirit Pet": "PET-SPIRIT-LEGENDARY",
  "Epic Spirit Pet": "PET-SPIRIT-EPIC",
  "Spirit Bow": "ITEM_SPIRIT_BOW",
  "Spirit Sword": "SPIRIT_SWORD",
  "Spirit Boots": "THORNS_BOOTS",
  "Spirit Stone": "SPIRIT_DECOY",
  "Wither Boots": "WITHER_BOOTS",
  "Wither Helmet": "WITHER_HELMET",
  "Wither Chestplate": "WITHER_CHESTPLATE",
  "Wither Leggings": "WITHER_LEGGINGS",
  "Wither Catalyst": "WITHER_CATALYST",
  "Precursor Gear": "PRECURSOR_GEAR",
  "Wither Cloak": "WITHER_CLOAK",
  "Wither Cloak Sword": "WITHER_CLOAK",
  "Wither Blood": "WITHER_BLOOD",
  Implosion: "IMPLOSION_SCROLL",
  "Shadow Warp": "SHADOW_WARP_SCROLL",
  "Wither Shield": "WITHER_SHIELD_SCROLL",
  "Auto Recombobulator": "AUTO_RECOMBOBULATOR",
  "Maxor The Fish": "MAXOR_THE_FISH",
  "Goldor The Fish": "GOLDOR_THE_FISH",
  "Storm The Fish": "STORM_THE_FISH",
  "Precursor Eye": "PRECURSOR_EYE",
  "Giant's Sword": "GIANTS_SWORD",
  "Necromancer Lord Chestplate": "NECROMANCER_LORD_CHESTPLATE",
  "Summoning Ring": "SUMMONING_RING",
  "Necromancer Sword": "NECROMANCER_SWORD",
  "Necromancer Lord Leggings": "NECROMANCER_LORD_LEGGINGS",
  "Necromancer Lord Helmet": "NECROMANCER_LORD_HELMET",
  "Sadan's Brooch": "SADAN_BROOCH",
  "Necromancer Lord Boots": "NECROMANCER_LORD_BOOTS",
  "Ancient Rose": "GOLEM_POPPY",
  "Swarm I": "ENCHANTED_BOOK-ULTIMATE_SWARM-1",
  "Giant Tooth": "GIANT_TOOTH",
  "Dark Orb": "DARK_ORB",
  "Lethality I": "ENCHANTED_BOOK-LETHALITY-6", // Typo on the wiki says Lethality I instead of VI
  "Lethality VI": "ENCHANTED_BOOK-LETHALITY-6",
  "Overload I": "ENCHANTED_BOOK-OVERLOAD-1",
  "Legion I": "ENCHANTED_BOOK-ULTIMATE_LEGION-1",
  "Shadow Fury": "SHADOW_FURY",
  "Last Breath": "LAST_BREATH",
  "Shadow Assassin Chestplate": "SHADOW_ASSASSIN_CHESTPLATE",
  "Livid Dagger": "LIVID_DAGGER",
  "Shadow Assassin Leggings": "SHADOW_ASSASSIN_LEGGINGS",
  "Warped Stone": "AOTE_STONE",
  "Shadow Assassin Helmet": "SHADOW_ASSASSIN_HELMET",
  "Shadow Assassin Boots": "SHADOW_ASSASSIN_BOOTS",
  "Kismet Feather": "KISMET_FEATHER",
};
